### ISSUE TITLE
Expected output not reflected when removing and adding items to the custom arraylist

### ISSUE THREAD

**Issue by rocheleerazonable** [thedarksamurai/skyeAssignment5#3]
Please refer to this recording https://screencast-o-matic.com/watch/c0nFnqVyDHG for further details

**Comment by thedarksamurai** [comment]
I removed the CustomArrayList app class and just with tests it should be running as expected

**Comment by rocheleerazonable** [comment]
Hi Skye, the main class is not the issue, pls double check your implementation so that the value of the items array will be as expected, I've provided expected output/contents of your array at each step of my example testcase. pls see screenshot here https://drive.google.com/file/d/1vzcvX2dA7wFdu7gT9qRYXsGu8FSD4kft/view?usp=sharing
